namespace HrServiceDesk.Application.Abstractions;

/// <summary>Stores attachment contents outside the database. Keys are generated by the storage, never by clients.</summary>
public interface IFileStorage
{
    Task<string> SaveAsync(Guid tenantId, Stream content, CancellationToken cancellationToken);

    Task<Stream> OpenReadAsync(string key, CancellationToken cancellationToken);

    Task DeleteAsync(string key, CancellationToken cancellationToken);
}
