// <auto-generated />
using System;
using HrServiceDesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HrServiceDesk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002091054_AddSlaEngine")]
    partial class AddSlaEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HrServiceDesk.Domain.Catalog.RequestType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultPriority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("default_priority");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FormSchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form_schema");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confidential");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ResponsibleTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_team_id");

                    b.Property<Guid?>("SlaPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_policy_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_request_types");

                    b.HasIndex("ResponsibleTeamId")
                        .HasDatabaseName("ix_request_types_responsible_team_id");

                    b.HasIndex("SlaPolicyId")
                        .HasDatabaseName("ix_request_types_sla_policy_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_request_types_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_request_types_tenant_id_name");

                    b.ToTable("request_types", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Sla.BusinessCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_business_calendars");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_business_calendars_tenant_id");

                    b.ToTable("business_calendars", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Sla.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AtRiskThresholdPercent")
                        .HasColumnType("integer")
                        .HasColumnName("at_risk_threshold_percent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string[]>("PauseStatuses")
                        .IsRequired()
                        .HasColumnType("character varying(32)[]")
                        .HasColumnName("pause_statuses");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sla_policies");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sla_policies_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sla_policies_tenant_id_name");

                    b.ToTable("sla_policies", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LastAssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_assigned_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("strategy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("LastAssignedUserId")
                        .HasDatabaseName("ix_teams_last_assigned_user_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_teams_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_tenant_id_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCulture")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("default_culture");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("field_key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_attachments_tenant_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_attachments_ticket_id");

                    b.HasIndex("UploadedById")
                        .HasDatabaseName("ix_attachments_uploaded_by_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comments_author_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_comments_tenant_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_comments_ticket_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("FirstRespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_responded_at");

                    b.Property<bool>("FirstResponseBreached")
                        .HasColumnType("boolean")
                        .HasColumnName("first_response_breached");

                    b.Property<DateTimeOffset?>("FirstResponseDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_response_due_at");

                    b.Property<int?>("FirstResponseTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("first_response_target_minutes");

                    b.Property<string>("FormData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form_data");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confidential");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_type_id");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<bool>("ResolutionBreached")
                        .HasColumnType("boolean")
                        .HasColumnName("resolution_breached");

                    b.Property<DateTimeOffset?>("ResolutionDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolution_due_at");

                    b.Property<int?>("ResolutionTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_target_minutes");

                    b.Property<int>("SlaAtRiskPercent")
                        .HasColumnType("integer")
                        .HasColumnName("sla_at_risk_percent");

                    b.Property<string[]>("SlaPauseStatuses")
                        .IsRequired()
                        .HasColumnType("character varying(32)[]")
                        .HasColumnName("sla_pause_statuses");

                    b.Property<Guid?>("SlaPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_policy_id");

                    b.Property<DateTimeOffset?>("SlaStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_started_at");

                    b.Property<string>("SlaState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sla_state");

                    b.Property<DateTimeOffset?>("SlaStoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_stopped_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_tickets_assignee_id");

                    b.HasIndex("RequestTypeId")
                        .HasDatabaseName("ix_tickets_request_type_id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_tickets_requester_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_tickets_team_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tickets_tenant_id");

                    b.HasIndex("SlaState", "ResolutionDueAt")
                        .HasDatabaseName("ix_tickets_sla_state_resolution_due_at");

                    b.HasIndex("TenantId", "AssigneeId")
                        .HasDatabaseName("ix_tickets_tenant_id_assignee_id");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_tenant_id_reference");

                    b.HasIndex("TenantId", "RequesterId")
                        .HasDatabaseName("ix_tickets_tenant_id_requester_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_tickets_tenant_id_status");

                    b.HasIndex("TenantId", "TeamId")
                        .HasDatabaseName("ix_tickets_tenant_id_team_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.TicketApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("approver_role");

                    b.Property<Guid?>("ApproverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedById")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("decision");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("step_name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_approvals");

                    b.HasIndex("DecidedById")
                        .HasDatabaseName("ix_ticket_approvals_decided_by_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ticket_approvals_tenant_id");

                    b.HasIndex("ApproverUserId", "Decision")
                        .HasDatabaseName("ix_ticket_approvals_approver_user_id_decision");

                    b.HasIndex("TicketId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_approvals_ticket_id_step_order");

                    b.ToTable("ticket_approvals", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.TicketEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ticket_events");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_ticket_events_actor_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ticket_events_tenant_id");

                    b.HasIndex("TicketId", "OccurredAt")
                        .HasDatabaseName("ix_ticket_events_ticket_id_occurred_at");

                    b.ToTable("ticket_events", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_refresh_tokens_tenant_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("LockoutEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_ends_at");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("character varying(32)[]")
                        .HasColumnName("roles");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_users_manager_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_type_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definitions");

                    b.HasIndex("RequestTypeId")
                        .HasDatabaseName("ix_workflow_definitions_request_type_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workflow_definitions_tenant_id");

                    b.HasIndex("TenantId", "RequestTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_definitions_tenant_id_request_type_id");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Infrastructure.Tickets.ReferenceCounter", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.HasKey("TenantId", "Year")
                        .HasName("pk_reference_counters");

                    b.ToTable("reference_counters", (string)null);
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Catalog.RequestType", b =>
                {
                    b.HasOne("HrServiceDesk.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleTeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_request_types_teams_responsible_team_id");

                    b.HasOne("HrServiceDesk.Domain.Sla.SlaPolicy", null)
                        .WithMany()
                        .HasForeignKey("SlaPolicyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_request_types_sla_policies_sla_policy_id");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Sla.BusinessCalendar", b =>
                {
                    b.OwnsMany("HrServiceDesk.Domain.Sla.WorkingInterval", "WorkingHours", b1 =>
                        {
                            b1.Property<Guid>("BusinessCalendarId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Day")
                                .HasColumnType("integer");

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time without time zone");

                            b1.HasKey("BusinessCalendarId", "Id");

                            b1.ToTable("business_calendars");

                            b1.ToJson("working_hours");

                            b1.WithOwner()
                                .HasForeignKey("BusinessCalendarId")
                                .HasConstraintName("fk_business_calendars_business_calendars_business_calendar_id");
                        });

                    b.OwnsMany("HrServiceDesk.Domain.Sla.Holiday", "Holidays", b1 =>
                        {
                            b1.Property<Guid>("CalendarId")
                                .HasColumnType("uuid")
                                .HasColumnName("calendar_id");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("CalendarId", "Date")
                                .HasName("pk_holidays");

                            b1.ToTable("holidays", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CalendarId")
                                .HasConstraintName("fk_holidays_business_calendars_calendar_id");
                        });

                    b.Navigation("Holidays");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Sla.SlaPolicy", b =>
                {
                    b.OwnsMany("HrServiceDesk.Domain.Sla.SlaTarget", "Targets", b1 =>
                        {
                            b1.Property<Guid>("SlaPolicyId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("FirstResponseMinutes")
                                .HasColumnType("integer");

                            b1.Property<string>("Priority")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("ResolutionMinutes")
                                .HasColumnType("integer");

                            b1.HasKey("SlaPolicyId", "Id");

                            b1.ToTable("sla_policies");

                            b1.ToJson("targets");

                            b1.WithOwner()
                                .HasForeignKey("SlaPolicyId")
                                .HasConstraintName("fk_sla_policies_sla_policies_sla_policy_id");
                        });

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Teams.Team", b =>
                {
                    b.HasOne("HrServiceDesk.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("LastAssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_teams_users_last_assigned_user_id");

                    b.OwnsMany("HrServiceDesk.Domain.Teams.TeamMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid")
                                .HasColumnName("team_id");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<int>("JoinedOrder")
                                .HasColumnType("integer")
                                .HasColumnName("joined_order");

                            b1.HasKey("TeamId", "UserId")
                                .HasName("pk_team_members");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("ix_team_members_user_id");

                            b1.ToTable("team_members", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TeamId")
                                .HasConstraintName("fk_team_members_teams_team_id");

                            b1.HasOne("HrServiceDesk.Domain.Users.User", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_team_members_users_user_id");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.Attachment", b =>
                {
                    b.HasOne("HrServiceDesk.Domain.Tickets.Ticket", null)
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_tickets_ticket_id");

                    b.HasOne("HrServiceDesk.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_users_uploaded_by_id");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.Comment", b =>
                {
                    b.HasOne("HrServiceDesk.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_author_id");

                    b.HasOne("HrServiceDesk.Domain.Tickets.Ticket", null)
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_tickets_ticket_id");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.Ticket", b =>
                {
                    b.HasOne("HrServiceDesk.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tickets_users_assignee_id");

                    b.HasOne("HrServiceDesk.Domain.Catalog.RequestType", null)
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_request_types_request_type_id");

                    b.HasOne("HrServiceDesk.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_users_requester_id");

                    b.HasOne("HrServiceDesk.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tickets_teams_team_id");

                    b.OwnsMany("HrServiceDesk.Domain.Sla.SlaPause", "SlaPauses", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("To")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("TicketId", "Id");

                            b1.ToTable("tickets");

                            b1.ToJson("sla_pauses");

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_tickets_tickets_ticket_id");
                        });

                    b.Navigation("SlaPauses");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.TicketApproval", b =>
                {
                    b.HasOne("HrServiceDesk.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_approvals_users_approver_user_id");

                    b.HasOne("HrServiceDesk.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("DecidedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_approvals_users_decided_by_id");

                    b.HasOne("HrServiceDesk.Domain.Tickets.Ticket", null)
                        .WithMany("Approvals")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_approvals_tickets_ticket_id");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.TicketEvent", b =>
                {
                    b.HasOne("HrServiceDesk.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_events_users_actor_id");

                    b.HasOne("HrServiceDesk.Domain.Tickets.Ticket", null)
                        .WithMany("Events")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_events_tickets_ticket_id");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("HrServiceDesk.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Users.User", b =>
                {
                    b.HasOne("HrServiceDesk.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_users_manager_id");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.HasOne("HrServiceDesk.Domain.Catalog.RequestType", null)
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_definitions_request_types_request_type_id");

                    b.OwnsMany("HrServiceDesk.Domain.Workflows.WorkflowStep", "Steps", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ApproverRole")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("approver_role");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<Guid>("WorkflowDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("workflow_definition_id");

                            b1.HasKey("Id")
                                .HasName("pk_workflow_steps");

                            b1.HasIndex("WorkflowDefinitionId")
                                .HasDatabaseName("ix_workflow_steps_workflow_definition_id");

                            b1.ToTable("workflow_steps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkflowDefinitionId")
                                .HasConstraintName("fk_workflow_steps_workflow_definitions_workflow_definition_id");
                        });

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("HrServiceDesk.Domain.Tickets.Ticket", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
