using System.Reflection;
using HrServiceDesk.Application.Abstractions;
using HrServiceDesk.Domain.Audit;
using HrServiceDesk.Domain.Catalog;
using HrServiceDesk.Domain.Common;
using HrServiceDesk.Domain.Escalations;
using HrServiceDesk.Domain.Integration;
using HrServiceDesk.Domain.Knowledge;
using HrServiceDesk.Domain.Notifications;
using HrServiceDesk.Domain.Sla;
using HrServiceDesk.Domain.Teams;
using HrServiceDesk.Domain.Tenants;
using HrServiceDesk.Domain.Tickets;
using HrServiceDesk.Domain.Users;
using HrServiceDesk.Domain.Workflows;
using HrServiceDesk.Infrastructure.Tickets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;

namespace HrServiceDesk.Infrastructure.Persistence;

public class AppDbContext : DbContext, IAppDbContext
{
    private static readonly MethodInfo ApplyTenantFilterMethod =
        typeof(AppDbContext).GetMethod(nameof(ApplyTenantFilter), BindingFlags.NonPublic | BindingFlags.Instance)!;

    private readonly ITenantContext _tenantContext;

    public AppDbContext(DbContextOptions<AppDbContext> options, ITenantContext tenantContext)
        : this((DbContextOptions)options, tenantContext)
    {
    }

    /// <summary>For derived contexts (tests) that bring their own options type.</summary>
    protected AppDbContext(DbContextOptions options, ITenantContext tenantContext)
        : base(options)
    {
        _tenantContext = tenantContext;
    }

    /// <summary>
    /// Read by the global query filters. EF Core re-evaluates context members on every query,
    /// so a pooled or long-lived model still filters by the tenant of the current scope.
    /// A <c>null</c> tenant matches no tenant-owned rows (secure default).
    /// </summary>
    public Guid? CurrentTenantId => _tenantContext.TenantId;

    public DbSet<Tenant> Tenants => Set<Tenant>();

    public DbSet<User> Users => Set<User>();

    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();

    public DbSet<PasswordResetToken> PasswordResetTokens => Set<PasswordResetToken>();

    public DbSet<RequestType> RequestTypes => Set<RequestType>();

    public DbSet<Ticket> Tickets => Set<Ticket>();

    public DbSet<Comment> Comments => Set<Comment>();

    public DbSet<Attachment> Attachments => Set<Attachment>();

    public DbSet<TicketEvent> TicketEvents => Set<TicketEvent>();

    public DbSet<TicketApproval> TicketApprovals => Set<TicketApproval>();

    public DbSet<WorkflowDefinition> WorkflowDefinitions => Set<WorkflowDefinition>();

    public DbSet<Team> Teams => Set<Team>();

    public DbSet<BusinessCalendar> BusinessCalendars => Set<BusinessCalendar>();

    public DbSet<SlaPolicy> SlaPolicies => Set<SlaPolicy>();

    public DbSet<Notification> Notifications => Set<Notification>();

    public DbSet<EscalationRule> EscalationRules => Set<EscalationRule>();

    public DbSet<EscalationExecution> EscalationExecutions => Set<EscalationExecution>();

    public DbSet<AuditLog> AuditLogs => Set<AuditLog>();

    public DbSet<KnowledgeArticle> KnowledgeArticles => Set<KnowledgeArticle>();

    public DbSet<SatisfactionRating> SatisfactionRatings => Set<SatisfactionRating>();

    public DbSet<ApiKey> ApiKeys => Set<ApiKey>();

    public DbSet<WebhookSubscription> WebhookSubscriptions => Set<WebhookSubscription>();

    public DbSet<WebhookDelivery> WebhookDeliveries => Set<WebhookDelivery>();

    internal DbSet<ReferenceCounter> ReferenceCounters => Set<ReferenceCounter>();

    public Task<IDbContextTransaction> BeginTransactionAsync(CancellationToken cancellationToken = default) =>
        Database.BeginTransactionAsync(cancellationToken);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // unaccent: accent-insensitive search in the help centre.
        modelBuilder.HasPostgresExtension("unaccent");
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);

        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            // Ids are generated by the domain (Entity), so new children reachable through a navigation
            // (comments, attachments, events) are recognised as inserts rather than updates.
            if (typeof(Entity).IsAssignableFrom(entityType.ClrType) && entityType.BaseType is null)
                modelBuilder.Entity(entityType.ClrType).Property(nameof(Entity.Id)).ValueGeneratedNever();

            if (typeof(ITenantOwned).IsAssignableFrom(entityType.ClrType) && entityType.BaseType is null)
            {
                ApplyTenantFilterMethod.MakeGenericMethod(entityType.ClrType).Invoke(this, [modelBuilder]);
            }
        }
    }

    private void ApplyTenantFilter<TEntity>(ModelBuilder modelBuilder)
        where TEntity : class, ITenantOwned
    {
        modelBuilder.Entity<TEntity>().HasQueryFilter(e => e.TenantId == CurrentTenantId);
        modelBuilder.Entity<TEntity>().HasIndex(e => e.TenantId);
    }
}
